projekt0n/github-nvim-theme

CHANGELOG.md
lua/lualine/themes/github.lua

After setting the `blue` color to `bg_statusline`, it's inherited inside the lualine `c` section.
- set `bg` color inside `c` section of lualine theme

Lualine background color fix

---

CHANGELOG.md
README.md
lua/github-theme/colors.lua
lua/github-theme/theme.lua

- Change `commentTSConstant` highlight to `c.syntax.keyword` from `c.syntax.commentConstant`
- Removed `commentConstant` color
- TODO list moved to #16

Change `commentTSConstant` highlight to `c.syntax.keyword`

---

CHANGELOG.md
lua/lualine/themes/github.lua

lualine `command` background fixed #30

lualine `command` background fixed #30

---

CHANGELOG.md
README.md
lua/github-theme/theme.lua

- Add **iTerm** support log inside `CHANGELOG.md` & `README.md`
- [README.md#plugin-support](https://github.com/projekt0n/github-nvim-theme#plugin-support) list updated
- **"kitty"** typo fixed inside `README.md`
- [ALE](https://github.com/dense-analysis/ale)
- [dashboard-nvim](https://github.com/glepnir/dashboard-nvim)
- [Indent Blankline](https://github.com/lukas-reineke/indent-blankline.nvim)
- [lspsaga.nvim](https://github.com/glepnir/lspsaga.nvim)
- [nvim-bufferline.lua](https://github.com/akinsho/nvim-bufferline.lua)
- [vim-gitgutter](https://github.com/airblade/vim-gitgutter)
- [which-key.nvim](https://github.com/folke/which-key.nvim/)

Additional plugin support (releated to #16)

---

CHANGELOG.md
lua/github-theme/colors.lua

- Make window-separator(`VertSplit`) highlight bright (related to #16)
- Removed unnecessary colors from `colors.lua`
- Merge conflict

Make window-separator(`VertSplit`) highlight bright (related to #16) 

---

CHANGELOG.md
README.md
extras/alacritty_github_dark.yml
extras/alacritty_github_dimmed.yml
extras/alacritty_github_light.yml
extras/iterm_github_dark.itermcolors
extras/iterm_github_dimmed.itermcolors
extras/iterm_github_light.itermcolors
extras/kitty_github_dark.conf
extras/kitty_github_dimmed.conf
extras/kitty_github_light.conf
extras/konsole_github_dark.colorscheme
extras/konsole_github_dimmed.colorscheme
extras/konsole_github_light.colorscheme
lua/github-theme/extra/iterm.lua
lua/github-theme/extra/kitty.lua

- Added Konsole theme log inside `CHANGELOG.md`
- **README.md#extra** renamed to `README.md#terminal-themes`
- `black` and `cyan` color hex changed
- Re-ordered key sections inside `lua/extra/iterm.lua`
- Removed comment from `kitty` themes

Regenerate terminal themes according to `colors.lua`

---

CHANGELOG.md
lua/github-theme/theme.lua

- Changed `TabLineSel` foreground color to `pmenu.select` fixed #35

`TabLineSel` barely readable foreground color fix

---

CHANGELOG.md
lua/github-theme/colors.lua
lua/github-theme/util.lua

- `github-theme.util.color_overrides` function support "NONE" color (fix related to #36)
- Enhanced `transparent` mode background color

Transparent mode enhacement

---

CHANGELOG.md
extras/iterm/dark.itermcolors
extras/iterm/dimmed.itermcolors
extras/iterm/light.itermcolors
extras/konsole/dark.colorscheme
extras/konsole/dimmed.colorscheme
extras/konsole/light.colorscheme
lua/github-theme/extra/init.lua
lua/github-theme/extra/konsole.lua

- Terminal themes are structured through `extra/init.lua`
- Add proper `Description` inside `konsole` theme (bug from #33)

Add proper `Description` inside `konsole` theme (bug from #33)

---

CHANGELOG.md
lua/github-theme/theme.lua

- Area for messages and cmdline with `bold` text highlight
- Update `CHANGELOG.md` logs.

Area for messages and cmdline with `bold` text highlight

---

CHANGELOG.md
README.md
lua/github-theme/colors.lua
lua/github-theme/config.lua
lua/github-theme/theme.lua

Enabling this option, will hide filler lines (~) after the end of the buffer.
`true`
- Separated colors for EndOfBuffer inisde colors.lua ( `eob` & `sidebar_eob` )
- Updated CHANGELOG.md
- Information added inisde README.md
- used `eob` & `sidebar_eob` colors inside theme.lua

`hideEndOfBuffer` options added

---

Makefile
extras/kitty/dark.conf
extras/kitty/dimmed.conf
extras/kitty/light.conf
lua/github-theme/extra/kitty.lua

- `make` commands source file path updated as of #39 
- `active_border_color` & `inactive_border_color` colors added inside kitty themes

Kitty Windows border color fixed

---

CHANGELOG.md
lua/github-theme/theme.lua

- Linked PR inside `CHANGELOG.md`
- `BufferLine` slant style separator color fixed ( related to #16)

`BufferLine` slant style separator color fixed ( related to #16)

---

CHANGELOG.md
README.md
lua/github-theme/config.lua
lua/github-theme/theme.lua

- `nvim-compe` highlight group added inisde `themes.lua`
- Removed `vimConfig` from `config.lua`

feat: `nvim-compe` plugin support

---

CHANGELOG.md
lua/github-theme/colors.lua

fix: Floating Windows background with `transparent` mode

---

CHANGELOG.md
README.md
lua/github-theme/theme.lua

- `javascriptTSStringRegex` foreground color fixed
- [barbar.nvim](https://github.com/romgrk/barbar.nvim) plugin support
- Update log inside `CHANGELOG.md`
- [README#plugin-support](https://github.com/projekt0n/github-nvim-theme#plugin-support) updated

`barbar.nvim` plugins support

---

CHANGELOG.md
README.md
lua/github-theme/config.lua
lua/github-theme/theme.lua

- `msgAreaStyle` config added
- Updated logs inside `CHANGELOG.md`
- config docs added inside `README.md`
```lua 
require("github-theme").setup({
msgAreaStyle = "NONE"
-- other config
})
```
check `:help highlight-args` for other options

feat: `msgAreaStyle` config added for customize message & cmdline 

---

CHANGELOG.md
lua/github-theme/colors.lua
lua/github-theme/theme.lua

- `border` color added in `colors.lua`
- telescope.nvim highlights improved
- use `bg_visiual` color as floating window border
- `CHANGELOG.md` logs updated

feat: telescope.nvim highlights improved

---

CHANGELOG.md
lua/github-theme/colors.lua
lua/github-theme/theme.lua

- Removed transparent config for `hideEndOfBuffer`.
- define `util.bg` color after `eob` colors assignment.
- Changelog updated
- Assign `eob` value to `NonText` highlight (inside `theme.lua`)
- Fixed #66

Set `NonText` & `EndOfBuffer` color value with `bg`

---

colors/github-dark.lua
colors/github-dimmed.lua
colors/github-light.lua

This allows setting them directly via `:colorscheme github-<variant>`.

✨ Add individual themes github-dark, github-dimmed and github-light

---

CHANGELOG.md
lua/github-theme/colors.lua
lua/github-theme/theme.lua

- `IncSearch` highlight linked with `Search`
- `Search` highlight enhanced for `transparent` mode
- `LineNr` highlight enhanced for `transparent` mode

fixes: transparent mode highlights

---

README.md

docs: colors override docs in `vim` config example

---

CHANGELOG.md
lua/github-theme/colors.lua
lua/github-theme/theme.lua

fix: NvimTree git highlight

---

CHANGELOG.md
README.md

missing `'` in vim config (README.md) 

---

CHANGELOG.md
lua/github-theme/colors.lua
lua/github-theme/theme.lua

- fg_statusline
- bg_nc_statusline

enhance: `StatusLine`  foreground color is customizable

---

CHANGELOG.md
lua/github-theme/colors.lua
lua/github-theme/theme.lua

- typo inisde `theme.lua`
- missing alias fixed inside `colors.lua`
- vscode like lspkind highlighting inside `nvim-cmp` #137 fixed

vscode like lspkind highlighting for `nvim-cmp` 

---

CHANGELOG.md
lua/github-theme/theme.lua

- custom highlights are removed from the `telescope.nvim`

Fix dark foreground color for visited entries in telescope.nvim

---

CHANGELOG.md
LUALINE.md
README.md
lua/github-theme/colors.lua
lua/github-theme/theme.lua

- Minimal look (`hide_inactive_statusline`) removed from lualine
- `terminal` highlight added for lualine
- Dark background color for inactive statusline with lualine plugin

Lualine and StatusLine enhancements, deprecation, and refactor

---

CHANGELOG.md
lua/github-theme/colors.lua
lua/github-theme/types/gt.lua
lua/github-theme/util.lua

- _getColor()_ removed from `util` module

feat: proper color docs with `gt.Palette` type

---

CHANGELOG.md
README.md
lua/github-theme/theme.lua

Hi! I would like to add explicit support for [mini.nvim](https://github.com/echasnovski/mini.nvim).
Basic choices are taken from highlight groups to which 'mini.nvim' makes links by default or from analogous plugins.
Differences from default linked groups:
- 'mini.cursorword' is based on 'Illuminate'.
- 'mini.jump2d' is based on 'Hop'.
- 'mini.starter' is based on 'dashboard.lua' and personal choices:
- `MiniStarterItemBullet` is as border.
- `MiniStarterItemPrefix` and `MiniStarterQuery` are based on "warning" and "info" diagnostic colors to be opposite of each other.
- `MiniStarterSection` is chosen to be visible.
- 'mini.statusline' is based on 'lualine/themes/tokyonight.lua' and personal choices:
- `MiniStatuslineDevinfo` and `MiniStatuslineFileinfo` have slightly different …

Add explicit support for 'mini.nvim'

---

CHANGELOG.md
lua/github-theme/theme.lua

I found an old PR, https://github.com/projekt0n/github-nvim-theme/pull/51, that seems to add support for this. It's marked as merged but it's not in the `main` branch. I dropped it back in and updated some things.

Add support for barbar.nvim

---

lua/github-theme/theme.lua

Added bufferline support to match the original
ref
https://github.com/primer/github-vscode-theme/blob/main/src/theme.js#L163
https://github.com/primer/primitives/blob/da4ffd338a41bb1f653e096c8b886db4834b3715/data/colors/vars/global_dark.ts#L100
https://github.com/primer/primitives/blob/cb66b57be785d2709acf82b272edf4f9e8243101/data/colors/themes/dark.ts#L56

feat: add highlight for BufferLineBackground

---

queries/typescript/highlights.scm

fix: delete custom query file which breaks typescript highlights

---

lua/github-theme/theme.lua

See discussion here:
https://github.com/projekt0n/github-nvim-theme/issues/201
Test result:
(underline does not work in `github_dark_default` & `github_dark`)

Add support for indent-blankline.nvim

---

lua/github-theme/init.lua
lua/github-theme/theme.lua

Hi there, I've translated the old treesitter group names to the new ones so this theme can support new treesitter versions.
This is what it looks like:

Support new treesitter group names

---

README.md

Fixes the tag (`0.0.7` to `v0.0.7`) in the Installation section of README.md.

docs: Fix tag `v0.0.7` in README.md

---

README.md

If applied, this commit will
- add a paragraph to `README.md` for installing `github-nvim-theme` with `lazy.nvim`

docs: added a paragraph for installing  with `lazy.nvim`

---

.github/workflows/update-colors.yml
.gitignore
package-lock.json
package.json

Introduce a GitHub workflow which runs on a schedule 3 times per week to pull in all of the ***exact*** color definitions for each theme directly from the `@primer/primitives` npm package. This pr adds a `package.json` file for clarity and for dependency tracking/declarations, as well as a new workflow file which is quite simple and uses npm. The workflow goes something like this:
1. Install the latest version of the `@primer/primitives` npm package in CI
2. Extract the color definition JSON files for each theme
3. Convert each JSON file to Lua, so that they can easily be required
4. Place these new Lua files under the new directory `lua/github-theme/palettes/primitives`
5. Run `make fmt` to format all Lua files
6. Use/run the `peter-evans/create-pull-request@v5` gh action, which will …

ci: Get and update primer primitives automatically

---

.github/workflows/update-color-primitives.yml

Fix typo: `lts` --> `lts/*`.
`lts` is an invalid node version alias. See: https://github.com/projekt0n/github-nvim-theme/actions/runs/5072809341
Rename `update-colors.yml` to `update-color-primitives.yml` as the latter is more descriptive.

ci(update-colors): fix typo

---

.github/workflows/update-color-primitives.yml

Problem:  the workflow is failing because `run: make fmt` invokes stylua,
and stylua is not available within ci by default.
Solution: use the action `JohnnyMorganz/stylua-action@v3` to install and
invoke stylua instead of just doing `run: make fmt`.
See https://github.com/projekt0n/github-nvim-theme/actions/runs/5094439816/jobs/9158251649#step:6:13

ci(update-colors): install stylua before using it

---

lua/github-theme/init.lua

Alternative fix to #269
The git path should be `./github-nvim-theme/.git` and not `./github-nvim-theme/lua/.git`
This change should fix the stale cache issue after user update the theme, see the videos below for validation:
https://github.com/projekt0n/github-nvim-theme/assets/56817415/ef91be3b-5085-47d7-891d-7ab332a36727
https://github.com/projekt0n/github-nvim-theme/assets/56817415/2cc6f117-3418-448c-a59b-6ff12304e891

fix(cache): wrong .git path

---

.github/workflows/update-color-primitives.yml

For whatever reason, the stylua action was not properly stripping the single quotes that are passed within the `args:` (even though this action uses [NodeJS `exec()`](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback) which says that it uses `/bin/sh` on Unix to execute the command-line...go figure). Anyway, the single quotes were removed.
Also, permissions required for the automated pull request to succeed were added.
---
I went through the hassle of making sure that [it actually works](https://github.com/tmillr/github-nvim-theme2/actions/runs/5137664526) this time because I've had the worst luck with this! lol. You can view the generated pr [here](https://github.com/tmillr/github-nvim-theme2/pull/3).
The only other requirement for this to work properly …

ci(update-colors): fix update-color-primitives.yml

---

lua/github-theme/group/modules/treesitter.lua
lua/github-theme/group/syntax.lua
queries/rust/highlights.scm

Rust lifetime highlights, and a few regex-based/legacy highlight corrections (#285).

fix(syntax-hl): misc corrections

---

CHANGELOG.md
Usage.md
doc/github-nvim-theme.txt
lua/github-theme/lib/compiler.lua
lua/github-theme/util/template.lua

feat: Implement highlight-blend feature

---

lua/github-theme/group/modules/treesitter.lua

Make labels the tag color (with exceptions for vimdoc, ruby, lua etc.). Previously un-highlighted labels are now highlighted.

fix(syntax-hl): link `@label` to `@tag`

---

README.md

After 806903c1b66a6b29347871922acd7d830a9d5c6a this setting was renamed from `enable` to `enabled`. Update REAME accordingly.
I just fought with this for a while, wondering why my sidebar (nvim-tree) wasn't being darkened :)

readme: update darken.sidebars.enabled

---

lua/github-theme/group/syntax.lua
lua/github-theme/lib/compiler.lua

For `Comment`, don't inherit style attributes (e.g. bold, italic) from other (e.g. overlayed) hl groups. For example, an inline-comment appearing after a markdown heading in a markdown file (heading highlighting extends to the end of the text line, including comments) can become/display bold due to inheriting style attributes. `nocombine` keeps this from happening.

fix(syntax-hl): set `nocombine` on Comment

---

queries/lua/highlights.scm

Within a function declaration, the entire function name should be the same color, regardless of whether it's a method etc., and including any punctuation within. This change introduces new treesitter-capture highlight groups which may each be independently overridden by the user.
Note: in Neovim, groups like `@x.y.z` fallback to `@x` implicitly if `@x.y.z` is not defined.

fix: lua function declaration name highlighting

---

lua/github-theme/_test/util.lua
lua/github-theme/palette/github_dark.lua
lua/github-theme/palette/github_dark_colorblind.lua
lua/github-theme/palette/github_dark_dimmed.lua
lua/github-theme/palette/github_dark_high_contrast.lua
lua/github-theme/palette/github_dark_tritanopia.lua
lua/github-theme/palette/github_light.lua
lua/github-theme/palette/github_light_colorblind.lua
lua/github-theme/palette/github_light_high_contrast.lua
lua/github-theme/palette/github_light_tritanopia.lua
test/github-theme/smoketest/startup_spec.lua

This should also correct any issues with the `Normal` bg being off or incorrect, as this color (i.e. the `Normal` bg, the global bg) ultimately derives from `canvas.default` (found in the palette).
Fixes #298

fix(palette): get `canvas` from primitives

---

CHANGELOG.md
lua/github-theme/config.lua
lua/github-theme/init.lua
lua/github-theme/lib/compiler.lua

Fix bug where the current theme gets compiled multiple times instead of compiling all themes.

fix(compiler): compile all themes inst of 1 mult times

---

lua/github-theme/group/modules/cmp.lua
lua/github-theme/group/modules/lsp_semantic_tokens.lua
lua/github-theme/group/modules/treesitter.lua
queries/bash/highlights.scm
queries/rust/highlights.scm
queries/solidity/highlights.scm

Redefine Treesitter capture groups

---

lua/github-theme/group/syntax.lua

Neovim 0.10 changes or removes some of the default links for builtin hl groups (e.g. "base" groups). As such, `Delimiter` (and its dependents) no longer link to `Special`. We rely on the default links for some of these builtin hl groups.
In `group/syntax.lua`, restore these default links by setting/recreating them explicitly instead of relying on the defaults.
This commit addresses the groups in `group/syntax.lua`, but there may be other files or groups that need to be similarly addressed.
Fixes #329

fix(syntax): incorrect highlight for `Delimiter`

---

.gitignore

This is useful when using a local cache folder for development.

chore: add `/cache` and `/.cache` to .gitignore

---

lua/github-theme/group/modules/mini.lua

Add explicit support for all new groups since #194 and for the (hopefully) upcoming 'mini.icons'.
Also format with consistent alignment.

feat(mini): add new highlight groups

---

CHANGELOG.md
README.md
lua/github-theme/_test/util.lua
lua/github-theme/config.lua
lua/github-theme/group/editor.lua
test/github-theme/config/darken_spec.lua

**Problem:** `options.darken.floats` isn't used anywhere and `NormalFloat` is unconditionally set to `spec.bg0` (darker background).
**Solution:** Only set `bg` of `NormalFloat` to `bg0` if `options.darken.floats` is `true`, otherwise, set it to `bg1` (default background).
**Problem:** Floating windows are darkened unconditionally and `options.darken.floats` appears to be documented as being `true` by default (see `options.darken` section of Usage.md), however, the actual default in `config.lua` is `false`. In README.md, the default value is properly documented as being `false`.
**Solution:** Change the default value of `options.darken.floats` to `true`. Update the documented default to `true`. This is not a breaking change because this is currently the default behavior.

fix(config): `options.darken.floats` is not used

---

lua/github-theme/override.lua

- Move the store into the module's metatable at `__index`.
- Setting a key to a falsy value resets the overrides under that key.
- Don't allow `has_override` to be modified externally.
- D.R.Y.

refactor(overrides): cleanup override.lua

---

CHANGELOG.md
lua/github-theme/_test/util.lua
lua/github-theme/group.lua
lua/github-theme/init.lua
lua/github-theme/override.lua
lua/github-theme/util/reload.lua
test/github-theme/config/darken_spec.lua
test/github-theme/config/overrides_spec.lua
test/minimal_init.vim

- Assigning `false` or an empty table to a highlight group clears it
- Assigning `false` to groups/specs/palettes clears previous settings from the config store (like `reset()` but finer-grained)
- (internal) Use `false` instead of `link = ''` to mark groups which should be cleared when set
- Improve `github-theme.group`
- Improve/cleanup code and other minor improvements (code-sharing, simplification, etc.)

feat(overrides): improve highlight-group overrides

---

CHANGELOG.md
lua/github-theme/_test/util.lua
lua/github-theme/init.lua
lua/github-theme/lib/compiler.lua
lua/github-theme/override.lua
test/github-theme/config/compiler_spec.lua
test/github-theme/smoketest/startup_spec.lua
test/minimal_init.vim

- Hash entire config instead of just the table passed to `setup()`. This helps to ensure that a re-compile occurs when overrides are set outside of `setup()`.
- Loading/sourcing colorscheme now causes recompilation if config or overrides have changed, even if `setup()` has been called before.
- Clear `vim.g.colors_name` before setting `vim.o.background` so that colorscheme is not reloaded recursively when setting `vim.o.background` (as opposed to using a variable to check for nested colorscheme load, which is what we were doing before).
- fix(compiler): always write hash to filesystem whenever a compilation occurs, incl. when `require('github-theme').compile()` is called directly.
Related: #262, #340, #341

fix(compiler): consider entire config when hashing

---

CHANGELOG.md
lua/github-theme/group/editor.lua
test/github-theme/config/transparent_spec.lua

fix: floats not transparent when `transparent = true`

---

CHANGELOG.md
README.md
Usage.md
doc/github-nvim-theme.txt
lua/github-theme/group/editor.lua
lua/github-theme/group/modules/neotree.lua
lua/github-theme/group/modules/nvimtree.lua
lua/github-theme/util/deprecation.lua
test/github-theme/config/darken_spec.lua

**Problem:** `options.darken.sidebars.enabled` and `options.darken.sidebars.enable` both exist, but it is only one option. The default in `config.lua` is `enable`, but it is referred to as `enabled` as well (both in code and docs). It used to be `enable` but was renamed to `enabled`, so it is technically supposed to be `options.darken.sidebars.enabled` at this time (as of this commit's parent).
**Solution:** Deprecate and revert `options.darken.sidebars.enabled` back to `options.darken.sidebars.enable`. This brings it back in-line with the changelog and runtime deprecation checks. `enable` is also more consistent as this is what is used in other parts of the config (e.g. config for `modules`).
**Problem:** In a couple of places, `options.darken.sidebars` is checked for truthiness. This …

fix(config): `options.darken.sidebars.enabled`

---

lua/github-theme/init.lua
lua/github-theme/palette.lua
lua/github-theme/spec.lua
lua/github-theme/util/template.lua
test/github-theme/config/darken_spec.lua

Remove duplicate/unneeded lines of code.

refactor(palette, spec): cleanup, DRY, add types

---

CHANGELOG.md
lua/github-theme/config.lua
lua/github-theme/group.lua
lua/github-theme/group/modules/cmp.lua
lua/github-theme/group/modules/coc.lua
lua/github-theme/group/modules/coc_explorer.lua
lua/github-theme/group/modules/dapui.lua
lua/github-theme/group/modules/dashboard.lua
lua/github-theme/group/modules/diagnostic.lua
lua/github-theme/group/modules/diffchar.lua
lua/github-theme/group/modules/fidget.lua
lua/github-theme/group/modules/fzf.lua
lua/github-theme/group/modules/gitgutter.lua
lua/github-theme/group/modules/gitsigns.lua
lua/github-theme/group/modules/indent_blankline.lua
lua/github-theme/group/modules/lsp_semantic_tokens.lua
lua/github-theme/group/modules/lsp_trouble.lua
lua/github-theme/group/modules/mini.lua
lua/github-theme/group/modules/native_lsp.lua
lua/github-theme/group/modules/neogit.lua
lua/github-theme/group/modules/neotree.lua
lua/github-theme/group/modules/notify.lua
lua/github-theme/group/modules/nvimtree.lua
lua/github-theme/group/modules/telescope.lua
lua/github-theme/group/modules/treesitter.lua
lua/github-theme/group/modules/treesitter_context.lua
lua/github-theme/group/modules/whichkey.lua
lua/github-theme/init.lua
lua/github-theme/lib/highlight.lua

Add and improve types (LSP) for groups, config, and modules.

refactor(config, modules): add types

---

.github/workflows/update-color-primitives.yml

- Run every 2 weeks (roughly) instead of 3x/week.
- Run on pull requests also, so that changes to the workflow file and its dependencies can be "tested" prior to merging. This does not run tests against the generated primitives however.

ci(primitives): run less often, run on pull requests

---

CHANGELOG.md
lua/github-theme/group/modules/treesitter.lua
lua/github-theme/init.lua
lua/github-theme/lib/color.lua
lua/github-theme/lib/compiler.lua
lua/github-theme/palette/github_dark.lua
lua/github-theme/palette/github_dark_colorblind.lua
lua/github-theme/palette/github_dark_default.lua
lua/github-theme/palette/github_dark_dimmed.lua
lua/github-theme/palette/github_dark_high_contrast.lua
lua/github-theme/palette/github_dark_tritanopia.lua
lua/github-theme/palette/github_light.lua
lua/github-theme/palette/github_light_colorblind.lua
lua/github-theme/palette/github_light_default.lua
lua/github-theme/palette/github_light_high_contrast.lua
lua/github-theme/palette/github_light_tritanopia.lua
test/github-theme/color_spec.lua

Fix bug where the colorscheme colors are off/incorrect when a palette is `require()`'d, whether directly or indirectly, anytime before compilation occurs (e.g. compilation that occurs during colorscheme load). For details, see issue #362.
Also, add a test (in `test/`) which disallows the direct or indirect use of the global static/class fields of the `Color` class (e.g. `Color.BG`).
Fixes: #362

fix(Color): don't use shared global state (`Color.BG` etc.)

---

README.md

If you try to install this colorscheme using lazy.nvim in the following way
```lua
{
"projekt0n/github-nvim-theme",
opts = {
options = {
transparent = true,
},
}
}
```
i.e., specifying some options in the `opts` field instead of using `config`, lazy cannot find the plugin.
To automatically call `setup` with the values of `opts`, it has to infer the name of the plugin from `projekt0n/github-nvim-theme`, resulting in `github-nvim-theme`. However, the plugin must be required with `require('github-theme')`.
You can manually specify the name of the plugin using the `name` field:
```lua
{
"projekt0n/github-nvim-theme",
name = "github-theme",
opts = {
options = {
transparent = true,
},
}
}
```

docs(README): specify `name` field in lazy.nvim installation
