CHANGELOG.md, extras/alacritty_github_dark.yml, extras/alacritty_github_dimmed.yml, extras/alacritty_github_light.yml, extras/kitty_github_dark.conf, extras/kitty_github_dimmed.conf, extras/kitty_github_light.conf, lua/github-theme/extra/alacritty.lua, lua/github-theme/extra/kitty.lua
- Kitty themes typo fixed #3
- Change the terminal background color to `bg` #2
=> Some terminal fixes

CHANGELOG.md, lua/github-theme/colors.lua, lua/github-theme/theme.lua
=> fixed #11: Added option to customize statusline background with `colors.bg_statusline`

CHANGELOG.md, lua/github-theme/colors.lua, lua/github-theme/theme.lua
Changes:
- illuminate plugin highlights fixed #10
https://user-images.githubusercontent.com/24286590/125270375-3bb6d680-e327-11eb-99c2-49f6013933f0.mp4
=> fixed #10: illuminate highlights

CHANGELOG.md, README.md, lua/github-theme/colors.lua, lua/github-theme/theme.lua
- Make `folded` colors configurable (related to #26)
- Removed support button from README.md
https://user-images.githubusercontent.com/24286590/125597430-c60d42c8-ff77-4868-8479-42f77a8dd4a5.mp4
=> `folded` colors are configurable

CHANGELOG.md, README.md, lua/github-theme/theme.lua
- Removed `fg_gutter` from neogit
- Updated [REAME.md#plugin-support](https://github.com/projekt0n/github-nvim-theme#plugin-support)
=> Neogit support (releated to #16)

lua/lualine/themes/github.lua
- lauline normal color fix to blue
=> lauline normal color fix

CHANGELOG.md, README.md, lua/github-theme/theme.lua
- [hop.nvim](https://github.com/phaazon/hop.nvim) plugin support
- Update log inside `CHANGELOG.md`
- [README#plugin-support](https://github.com/projekt0n/github-nvim-theme#plugin-support) updated
=> feat: hop.nvim plugin support

CHANGELOG.md, lua/github-theme/theme.lua, lua/github-theme/util.lua
- loadtime decreased by re-patching ful1e5/onedark.nvim#2
=> loadtime decreased by re-patching hide lualine bug

CHANGELOG.md, Makefile, README.md, extras/tmux/dark.tmux, extras/tmux/dimmed.tmux, extras/tmux/light.tmux, lua/github-theme/extra/alacritty.lua, lua/github-theme/extra/init.lua, lua/github-theme/extra/iterm.lua, lua/github-theme/extra/kitty.lua, lua/github-theme/extra/konsole.lua, lua/github-theme/extra/tmux.lua
- added **tmux** theme #23
- parameter docs added inside `lua/extra/*`
- make commands added for reloading the tmux theme
- changes logs updated
=> feat: tmux theme support

CHANGELOG.md, README.md, lua/github-theme/colors.lua, lua/github-theme/theme.lua
=> feat: nvim-web-devicons colors updated (releated to #16)

CHANGELOG.md, lua/github-theme/colors.lua, lua/github-theme/theme.lua
=> feat: Set `border` colors according to `themeStyle`

CHANGELOG.md, lua/github-theme/colors.lua, lua/lualine/themes/github.lua
=> fix: lualine colors with bg color support #80 

CHANGELOG.md, README.md, lua/github-theme/theme.lua
=> enhance: highlight all lspkind list in `nvim-cmp`

CHANGELOG.md, README.md
=> release v0.0.3

CHANGELOG.md, lua/github-theme/theme.lua
- patch removed `hop.nvim` highlights
- #144 fixed
=> Repatch removed hop.nvim highlights

CHANGELOG.md, lua/github-theme/theme.lua
=> Fix highlights of inactive tabline in lualine plugin

.luarc.json, CHANGELOG.md, README.md, lua/github-theme/colors.lua
- add: define global in project `luarc` config file.
=>  inherit `eof` color from `fg_gutter`

CHANGELOG.md, README.md, lua/github-theme/config.lua, lua/github-theme/theme.lua, lua/github-theme/util.lua
- allow customizing highlight group ful1e5/onedark.nvim#91
- Removed unnecessary defer function & highlights
=> feat: allow customizing highlight group

terminal/windows-terminal/github_dark.json, terminal/windows-terminal/github_dark_colorblind.json, terminal/windows-terminal/github_dark_default.json, terminal/windows-terminal/github_dimmed.json, terminal/windows-terminal/github_light.json, terminal/windows-terminal/github_light_colorblind.json, terminal/windows-terminal/github_light_default.json
Copied over the existing theme values to the appropriate JSON values for Windows Terminal.
=> feat: add terminal themes for Windows Terminal

lua/github-theme/plugins/lualine.lua
This PR makes transparent background of the lualine empty sections.
For Light Mode and Other theme as well it makes transparent background.
=> feat: transparent background on lualine empty sections

lua/github-theme/plugins/lualine.lua
Reverts projekt0n/github-nvim-theme#192
=> Revert "feat: transparent background on lualine empty sections"

README.md
=> docs: improve visibility of note

CHANGELOG.md, README.md, autoload/airline/themes/github_dark.vim, autoload/airline/themes/github_dark_colorblind.vim, autoload/airline/themes/github_dark_default.vim, autoload/airline/themes/github_dark_dimmed.vim, autoload/airline/themes/github_dark_high_contrast.vim, autoload/airline/themes/github_dark_tritanopia.vim, autoload/airline/themes/github_light.vim, autoload/airline/themes/github_light_colorblind.vim, autoload/airline/themes/github_light_high_contrast.vim, autoload/airline/themes/github_light_tritanopia.vim, lua/github-theme/util/airline.lua
=> feat: Added Airline themes

CHANGELOG.md, doc/gt_changelog.txt
=> docs: Fixed changelog mistakes

CHANGELOG.md, lua/github-theme/group/editor.lua, lua/github-theme/palette/github_dark.lua, lua/github-theme/palette/github_dark_colorblind.lua, lua/github-theme/palette/github_dark_dimmed.lua, lua/github-theme/palette/github_dark_high_contrast.lua, lua/github-theme/palette/github_dark_tritanopia.lua, lua/github-theme/palette/github_light.lua, lua/github-theme/palette/github_light_colorblind.lua, lua/github-theme/palette/github_light_high_contrast.lua, lua/github-theme/palette/github_light_tritanopia.lua
=> chore: Enhance current Statusline and Popup selection colors

CHANGELOG.md, autoload/airline/themes/github_dark_high_contrast.vim
=> fix: typo in `github_dark_high_contrast` airline theme

CHANGELOG.md, lua/github-theme/config.lua, lua/github-theme/group/modules/coc_explorer.lua
=> feat: Add coc-explorer support

queries/solidity/highlights.scm
Attempting to resolve the issue with Solidity.
Closes #322 
Not sure how to test this.
The highlight file was taken from: https://github.com/JoranHonig/tree-sitter-solidity/blob/master/queries/highlights.scm
=> Add highlights for Solidity
